# Generated by Django 5.1.4 on 2026-07-12 13:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JournalSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('00000000-0000-0000-0000-000000000001'), editable=False, primary_key=True, serialize=False)),
                ('journal_name_ru', models.CharField(max_length=255)),
                ('journal_name_en', models.CharField(max_length=255)),
                ('issn', models.CharField(blank=True, max_length=16)),
                ('about_ru', models.TextField()),
                ('about_en', models.TextField()),
                ('editorial_board', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Journal settings',
                'verbose_name_plural': 'Journal settings',
                'db_table': 'journal_settings',
            },
        ),
    ]
