# Generated by Django 5.1.4 on 2026-07-13 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalsettings',
            name='guidelines_for_authors_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='journalsettings',
            name='guidelines_for_authors_ru',
            field=models.TextField(blank=True),
        ),
    ]
