# Generated by Django 5.1.4 on 2026-07-12 13:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorialDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('accept', 'Принять'), ('reject', 'Отклонить'), ('revise', 'На доработку')], max_length=16)),
                ('comment', models.TextField()),
                ('stage', models.CharField(choices=[('topic_check', 'Проверка тематики'), ('review_decision', 'Решение по рецензиям')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='articles.article')),
            ],
            options={
                'db_table': 'editorial_decisions',
                'ordering': ['-created_at'],
            },
        ),
    ]
