# Generated by Django 5.1.4 on 2026-07-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editorialdecision',
            name='stage',
            field=models.CharField(choices=[('completeness_check', 'Проверка комплектности'), ('topic_check', 'Проверка тематики'), ('review_decision', 'Решение по рецензиям')], max_length=32),
        ),
    ]
