# Generated by Django 5.1.4 on 2026-07-12 13:00

import apps.articles.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleAuthor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('affiliation', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'article_authors',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ArticleDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(max_length=128)),
                ('file', models.FileField(upload_to=apps.articles.models.document_upload_path)),
            ],
            options={
                'db_table': 'article_documents',
            },
        ),
        migrations.CreateModel(
            name='ArticleVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('manuscript_file', models.FileField(upload_to=apps.articles.models.manuscript_upload_path)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('author_comment', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'article_versions',
                'ordering': ['version_number'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title_ru', models.CharField(max_length=512)),
                ('title_en', models.CharField(max_length=512)),
                ('abstract_ru', models.TextField()),
                ('abstract_en', models.TextField()),
                ('keywords_ru', models.JSONField(blank=True, default=list)),
                ('keywords_en', models.JSONField(blank=True, default=list)),
                ('topic', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'На рассмотрении'), ('needs_revision', 'Требуется доработка'), ('rejected', 'Отклонена'), ('in_review', 'Рецензируется'), ('accepted', 'Принята к публикации'), ('published', 'Опубликована')], default='draft', max_length=32)),
                ('doi', models.CharField(blank=True, max_length=128)),
                ('pages_count', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_autosaved_at', models.DateTimeField(blank=True, null=True)),
                ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='issues.issue')),
            ],
            options={
                'db_table': 'articles',
                'ordering': ['-created_at'],
            },
        ),
    ]
