# Generated by Django 5.1.4 on 2026-07-12 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articleauthor',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='articles.article'),
        ),
        migrations.AddField(
            model_name='articleauthor',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='co_authored_articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articleversion',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='articles.article'),
        ),
        migrations.AddField(
            model_name='articledocument',
            name='article_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='articles.articleversion'),
        ),
        migrations.AlterUniqueTogether(
            name='articleversion',
            unique_together={('article', 'version_number')},
        ),
    ]
