# Generated by Django 5.1.4 on 2026-07-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='completeness_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
