# Generated by Django 5.1.4 on 2026-07-12 13:00

import apps.issues.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description_ru', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=apps.issues.models.cover_upload_path)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('en', 'English'), ('mixed', 'Смешанный')], default='mixed', max_length=8)),
            ],
            options={
                'db_table': 'issues',
                'ordering': ['-year', '-number'],
                'unique_together': {('number', 'year')},
            },
        ),
    ]
