# Generated by Django 5.1.4 on 2026-07-12 13:00

import apps.reviews.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invitation_status', models.CharField(choices=[('invited', 'Приглашён'), ('accepted', 'Принято'), ('declined', 'Отклонено')], default='invited', max_length=16)),
                ('deadline', models.DateField()),
                ('recommendation', models.CharField(blank=True, choices=[('accept', 'Принять'), ('revise', 'На доработку'), ('reject', 'Отклонить')], max_length=16)),
                ('review_form_data', models.JSONField(blank=True, null=True)),
                ('review_file', models.FileField(blank=True, null=True, upload_to=apps.reviews.models.review_upload_path)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='articles.article')),
            ],
            options={
                'db_table': 'reviews',
                'ordering': ['-deadline'],
            },
        ),
    ]
