# Generated by Django 5.1.4 on 2026-07-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='invitation_status',
            field=models.CharField(choices=[('invited', 'Приглашён'), ('accepted', 'Принято'), ('declined', 'Отклонено'), ('cancelled', 'Аннулировано')], default='invited', max_length=16),
        ),
    ]
