# Generated by Django 5.1.4 on 2026-07-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_review_invitation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='author_replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='author_reply_file',
            field=models.FileField(blank=True, null=True, upload_to='author_replies/'),
        ),
        migrations.AddField(
            model_name='review',
            name='author_reply_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='review',
            name='conclusions_supported',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='review',
            name='conflict_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='review',
            name='conflict_of_interest',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='consent_wos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='english_quality',
            field=models.CharField(blank=True, choices=[('needs_improvement', 'The English could be improved'), ('fine', 'The English is fine')], max_length=20),
        ),
        migrations.AddField(
            model_name='review',
            name='ethical_concerns',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='figures_tables_clear',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='review',
            name='interest_to_readers',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='review',
            name='intro_background',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='review',
            name='methods_adequate',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='review',
            name='no_ai_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='originality',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='review',
            name='plagiarism_detected',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='presentation_quality',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='review',
            name='research_design',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='review',
            name='results_clear',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='review',
            name='scientific_soundness',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='review',
            name='sign_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='significance',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
