# Generated by Django 5.1.4 on 2026-07-23 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_review_author_replied_at_review_author_reply_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='ethical_concerns',
            new_name='ethical_issues',
        ),
        migrations.RemoveField(
            model_name='review',
            name='author_replied_at',
        ),
        migrations.RemoveField(
            model_name='review',
            name='author_reply_file',
        ),
        migrations.RemoveField(
            model_name='review',
            name='author_reply_text',
        ),
        migrations.RemoveField(
            model_name='review',
            name='conclusions_supported',
        ),
        migrations.RemoveField(
            model_name='review',
            name='conflict_details',
        ),
        migrations.RemoveField(
            model_name='review',
            name='consent_wos',
        ),
        migrations.RemoveField(
            model_name='review',
            name='english_quality',
        ),
        migrations.RemoveField(
            model_name='review',
            name='figures_tables_clear',
        ),
        migrations.RemoveField(
            model_name='review',
            name='interest_to_readers',
        ),
        migrations.RemoveField(
            model_name='review',
            name='intro_background',
        ),
        migrations.RemoveField(
            model_name='review',
            name='methods_adequate',
        ),
        migrations.RemoveField(
            model_name='review',
            name='no_ai_used',
        ),
        migrations.RemoveField(
            model_name='review',
            name='originality',
        ),
        migrations.RemoveField(
            model_name='review',
            name='presentation_quality',
        ),
        migrations.RemoveField(
            model_name='review',
            name='research_design',
        ),
        migrations.RemoveField(
            model_name='review',
            name='results_clear',
        ),
        migrations.RemoveField(
            model_name='review',
            name='scientific_soundness',
        ),
        migrations.RemoveField(
            model_name='review',
            name='sign_review',
        ),
        migrations.RemoveField(
            model_name='review',
            name='significance',
        ),
        migrations.AddField(
            model_name='review',
            name='article_rating',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='review',
            name='evaluation_rating',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='review',
            name='language_quality',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
